### ISSUE TITLE
Contribute this to Python stdlib?

### ISSUE THREAD

**Issue by singingwolfboy** [llllllllll/cnamedtuple#3]
Hey Joe, I remember you mentioning that you wanted to contribute this project to the Python standard library. Any progress on that?

**Comment by llllllllll** [comment]
I have discussed this with Raymond Hettinger and he convinced me that it was best to not make this change. This is a lot of hard to maintain code which is much more difficult to debug than the current implementation. The current stdlib implementation also leverages `property` so that any changes there make nametuple better. Instead, I worked on a performance patch for `property.__get__` which was accepted into 3.5.

**Comment by singingwolfboy** [comment]
Disappointing, but understandable. Maybe you could add a section in the README that describes how to install the project from Pip, and how to import it (with a fallback to stdlib namedtuple). It would be nice for other Python applications to be able to use the performance improvements you've implemented!

Also, maybe this is a naive question, but how well does code run on PyPy? Do you think they would be amenable to having this code integrated there?

**Comment by llllllllll** [comment]
I normally don't work to support pypy; however, I imagine that if it worked it would be slower. pypy has some strong assumptions about the performance of a property so it is a very fast code path. I could add something that showed a fallback style import. For example:

``` python
try:
    from cnamedtuple import namedtuple
except ImportError:
    from collections import namedtuple
```

Side note: do CPython extension modules run on pypy at all?

**Comment by singingwolfboy** [comment]
I know that the way to run C extensions on PyPy is using [cffi](https://cffi.readthedocs.org) (the C Foreign Function Interface). I don't know how this works -- I've never written a C extension for Python, so I don't know how similar or different it is to use cffi vs your approach.

**Comment by llllllllll** [comment]
That looks like it is designed for interfacing with arbitrary C. This is written with the explicit CPython API in mind and takes advantage of things like the struct layout of a tuple object. Unfortunatly I cannot see this working on pypy in a sane way.
