### ISSUE TITLE
Provide benchmarks in the README

### ISSUE THREAD

**Issue by giampaolo** [llllllllll/cnamedtuple#7]
There recently has been a discussion about namedtuple performance in cPython:
https://mail.python.org/pipermail/python-dev/2017-July/148592.html 

It has also been suggested to reimplement namedtuple in C and this project was signaled as a possible source to look into:
http://bugs.python.org/issue28638

As such it would be great to have some solid benchmarks showing the  actual speedup. Something similar to this:
https://gist.github.com/teepark/1003105

**Comment by llllllllll** [comment]
I have added a benchmark suite: https://github.com/llllllllll/cnamedtuple/blob/master/bench

I will run a full benchmark suite tonight but the output looks like:

```
$ ./bench -n 2
Running with: Python 3.6.1 (default, Mar 27 2017, 00:27:06) [GCC 6.3.1 20170306]

type creation from string with 1 field(s): namedtuple('NT', 'a')
  collections: 256 us +- 14 us
  cnamedtuple: 6.60 us +- 0.51 us
  ratio:       38.82

type creation from string with 2 field(s): namedtuple('NT', 'a b')
  collections: 290 us +- 47 us
  cnamedtuple: 7.09 us +- 0.28 us
  ratio:       40.93

type creation from sequence with 1 field(s): namedtuple('NT', ['a'])
  collections: 262 us +- 10 us
  cnamedtuple: 6.55 us +- 0.34 us
  ratio:       40.02

...
```

**Comment by llllllllll** [comment]
I added the full results for classes with up to eight fields (it can be run with more but who does that?) to the README.
